application: tweetbak
version: 2
runtime: python
api_version: 1


handlers:
- url: /static
  static_dir: static

- url: .*
  script: main.py

- url: /tasks/refresh
  script: main.py
  login: admin

builtins:
- datastore_admin: on
